# Generated by Django 4.2.1 on 2023-06-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.FloatField(help_text='in minutes')),
                ('difficulty', models.CharField(max_length=20)),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
